### ISSUE TITLE
Error on php 8.0

### ISSUE THREAD

**Issue by pinclau** [dotkernel/dot-form#7]
On php 8.0 FormAbstractServiceFactory does not extend any class and return parent method canCreate(). 
you need only to extend LoggerAbstractServiceFactory  without implements AbstractFactoryInterface because is already implemented from LoggerAbstractServiceFactory .

**Comment by arhimede** [comment]
@bidi47 introduced in https://github.com/dotkernel/dot-form/pull/5/files
